FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "streaming/publisher.py", "--csv", "data/test.csv", "--speed", "0.5"]
